In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/nycu-dilab-2023-onboard/data_train.csv
/kaggle/input/nycu-dilab-2023-onboard/data_test.csv
/kaggle/input/nycu-dilab-2023-onboard/answer_train.csv
/kaggle/input/nycu-dilab-2023-onboard/answer_sample.csv


# Task Instructions

Step 0. Import **ALL** packages you need in **ONE** cell   

Step 1. Load Data

Step 2. Model Comparison and Discussion 

Step 3. Conclusion

 

# Step 0. Import **ALL** packages you need in **ONE** cell  

In [2]:
import pandas as pd
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn import tree
from sklearn.metrics import confusion_matrix
from sklearn.metrics import recall_score,accuracy_score
from sklearn.metrics import precision_score
from sklearn.model_selection import train_test_split

import csv
import time

def generate_csv(ypredict, filename = 'result.csv'):
    with open(filename,'w',newline = '') as fd:
        writer = csv.writer(fd)
        writer.writerow(['index','default.payment.next.month'])

    for index,pred in enumerate(ypredict):
        with open(filename,'a',newline = '') as fd:
            writer = csv.writer(fd)
            writer.writerow([index,pred])
            
def show_result(groud_truth, prediction):
    print("Accuracy: ", accuracy_score(groud_truth, prediction))
    print("Precision: ",precision_score(groud_truth, prediction))
    print("Recall: ",recall_score(groud_truth, prediction))
    print("Confusion Matrix: ")
    print(confusion_matrix(groud_truth, prediction))
    return accuracy_score(groud_truth, prediction)

# Step 1. Load Data

In [3]:
train_x = pd.read_csv('/kaggle/input/nycu-dilab-2023-onboard/data_train.csv')
train_x = train_x.iloc[:,1:-1]
train_y = pd.read_csv('/kaggle/input/nycu-dilab-2023-onboard/answer_train.csv')
train_y = train_y.iloc[:,-1]
test_x = pd.read_csv('/kaggle/input/nycu-dilab-2023-onboard/data_test.csv')
test_x = test_x.iloc[:,1:-1]
train_split_x, valid_x, train_split_y, valid_y = train_test_split(train_x, train_y, test_size = 0.2, random_state = 1)

# Step 2. Algorithms Comparison and Discussion 

**"In addition to the parameters listed, please provide an analytical discussion for each model as described below. You can also supplement any other parameters that were found to have an impact on the model during the process."**

* Linear Regression: L1/L2   - The weight difference of different features under L1 and L2
* Decision Tree: IG/Gini - The difference between the results of two different index pairs
* Support Vector Machine: Gamma/C - The effect of each of the two parameters on the model
* K-Nearest Neighbor: K  - Effect of different K values on the model


### Linear Regression ###

In [4]:
#L1
model=Lasso(alpha = 0.1)
model.fit(train_split_x, train_split_y)

ypredict = model.predict(valid_x).round()
ypredict[ypredict>1] = 1
ypredict[ypredict<1] = 0
show_result(valid_y, ypredict)

model=Lasso(alpha = 0.1)
model.fit(train_x, train_y)
ypredict=model.predict(test_x).round()
ypredict[ypredict>1] = 1
ypredict[ypredict<1] = 0
generate_csv(ypredict, 'L1_Result.csv')

print("Coefficients:")
for feature, coef in zip(train_x.columns, model.coef_):
    print(f"{feature}: {coef}")

Accuracy:  0.7895833333333333
Precision:  0.0
Recall:  0.0
Confusion Matrix: 
[[3790    0]
 [1010    0]]


/opt/conda/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Coefficients:
LIMIT_BAL: -3.86213945302264e-07
SEX: -0.0
EDUCATION: -0.0
MARRIAGE: -0.0
AGE: 0.00034047611985944554
PAY_0: 0.022401881075170705
PAY_2: 0.0
PAY_3: 0.0
PAY_4: 0.0
PAY_5: 0.0
PAY_6: 0.0
BILL_AMT1: -7.330477628529089e-07
BILL_AMT2: 4.883057226018414e-07
BILL_AMT3: 8.583291115355317e-08
BILL_AMT4: -3.255685105450036e-08
BILL_AMT5: -9.74364560126634e-10
BILL_AMT6: 5.131143588389601e-07
PAY_AMT1: -1.283267024562784e-06
PAY_AMT2: -3.7693352700557296e-07
PAY_AMT3: -1.817371420417261e-07
PAY_AMT4: -5.309567091377825e-07
PAY_AMT5: -8.237826765092349e-07


In [5]:
#L2
model=Ridge(alpha = 100)
model.fit(train_split_x, train_split_y)

ypredict = model.predict(valid_x).round()
ypredict[ypredict>1] = 1
ypredict[ypredict<1] = 0
show_result(valid_y, ypredict)

model=Ridge(alpha = 0.1)
model.fit(train_x, train_y)
ypredict=model.predict(test_x).round()
ypredict[ypredict>1] = 1
ypredict[ypredict<1] = 0
generate_csv(ypredict, 'L2_Result.csv')

print("Coefficients:")
for feature, coef in zip(train_x.columns, model.coef_):
    print(f"{feature}: {coef}")

Accuracy:  0.80875
Precision:  0.7277227722772277
Recall:  0.14554455445544554
Confusion Matrix: 
[[3735   55]
 [ 863  147]]
Coefficients:
LIMIT_BAL: -7.429199713770805e-08
SEX: -0.014256801877172189
EDUCATION: -0.014601901052716587
MARRIAGE: -0.024057311147190147
AGE: 0.0013108988209303862
PAY_0: 0.0952428030501068
PAY_2: 0.01828489284009101
PAY_3: 0.014216678008888844
PAY_4: 0.0009659921663427467
PAY_5: 0.008554273190545105
PAY_6: 0.0007388271315350133
BILL_AMT1: -7.65211248555743e-07
BILL_AMT2: 2.752711639393993e-07
BILL_AMT3: 7.374113850745361e-08
BILL_AMT4: -1.1944062769852974e-07
BILL_AMT5: -1.672200671223398e-07
BILL_AMT6: 2.7364896426665346e-07
PAY_AMT1: -8.473424323207212e-07
PAY_AMT2: -2.3913311990434064e-07
PAY_AMT3: 3.8849580501954106e-08
PAY_AMT4: -2.005214981109826e-07
PAY_AMT5: -5.806097865513522e-07


### Decision Tree ###

In [6]:
#information gain
model=DecisionTreeClassifier(criterion = 'entropy', max_depth = 4, random_state=1)
model.fit(train_split_x, train_split_y)

ypredict = model.predict(valid_x)
show_result(valid_y, ypredict)

model=DecisionTreeClassifier(criterion = 'entropy', max_depth = 4, random_state=1)
model.fit(train_x, train_y)
ypredict=model.predict(test_x)
generate_csv(ypredict, 'DTIG_Result.csv')

Accuracy:  0.82875
Precision:  0.6721611721611722
Recall:  0.36336633663366336
Confusion Matrix: 
[[3611  179]
 [ 643  367]]


In [7]:
#gini impurity
model=DecisionTreeClassifier(criterion = 'gini', max_depth = 4, random_state=1)
model.fit(train_split_x, train_split_y)

ypredict = model.predict(valid_x)
show_result(valid_y, ypredict)

model=DecisionTreeClassifier(criterion = 'gini', max_depth = 4, random_state=1)
model.fit(train_x, train_y)
ypredict=model.predict(test_x)
generate_csv(ypredict, 'DTgini_Result.csv')

Accuracy:  0.8277083333333334
Precision:  0.6678899082568808
Recall:  0.3603960396039604
Confusion Matrix: 
[[3609  181]
 [ 646  364]]


### Support Vector Machine ###

In [8]:
# Training the SVM model
start = time.time()
model = SVC(kernel='linear', random_state=1)
model.fit(train_split_x, train_split_y)
print("Training time: ", time.time() - start)
print()

# Evaluating the SVM model on the validation set
ypredict = model.predict(valid_x)
show_result(valid_y, ypredict)

# Generating CSV file for the SVM model's predictions on the test set
model = SVC(kernel='linear', random_state=1)
model.fit(train_x, train_y)
ypredict = model.predict(test_x)
generate_csv(ypredict, 'SVM_Result.csv')

Training time:  14236.021749258041

Accuracy:  0.7735416666666667
Precision:  0.4123006833712984
Recall:  0.1792079207920792
Confusion Matrix: 
[[3532  258]
 [ 829  181]]


In [9]:
# Training the SVM model
start = time.time()
model = SVC(kernel='rbf', class_weight = 'balanced', random_state=1)
model.fit(train_split_x, train_split_y)
print("Gamma: ", model._gamma)
print("Training time: ", time.time() - start)
print()

# Evaluating the SVM model on the validation set
ypredict = model.predict(valid_x)
show_result(valid_y, ypredict)

# Generating CSV file for the SVM model's predictions on the test set
model = SVC(kernel='rbf', class_weight = 'balanced', random_state=1)
model.fit(train_x, train_y)
ypredict = model.predict(test_x)
generate_csv(ypredict, 'SVM_rbf_Result.csv')

Gamma:  1.3202465493710435e-11
Training time:  23.763117790222168

Accuracy:  0.5747916666666667
Precision:  0.2872472141972761
Recall:  0.689108910891089
Confusion Matrix: 
[[2063 1727]
 [ 314  696]]


### K-Nearest Neighbor ###

In [10]:
neighbors = [5,10,20,50,100,200]
best_acc = 0
for i in neighbors:
    model=KNeighborsClassifier(n_neighbors = i)
    model.fit(train_split_x, train_split_y)
    print("N =", i)

    ypredict = model.predict(valid_x)
    acc = show_result(valid_y, ypredict)
    print()
    if acc > best_acc:
        best_acc = acc
        best_n = i    

model=KNeighborsClassifier(n_neighbors = 50)
model.fit(train_x, train_y)
ypredict=model.predict(test_x)
generate_csv(ypredict, 'KNN_Result.csv')

N = 5
Accuracy:  0.7664583333333334
Precision:  0.38742393509127787
Recall:  0.1891089108910891
Confusion Matrix: 
[[3488  302]
 [ 819  191]]

N = 10
Accuracy:  0.7872916666666666
Precision:  0.4751131221719457
Recall:  0.10396039603960396
Confusion Matrix: 
[[3674  116]
 [ 905  105]]

N = 20
Accuracy:  0.7885416666666667
Precision:  0.48366013071895425
Recall:  0.07326732673267326
Confusion Matrix: 
[[3711   79]
 [ 936   74]]

N = 50
Accuracy:  0.7902083333333333
Precision:  0.5151515151515151
Recall:  0.0504950495049505
Confusion Matrix: 
[[3742   48]
 [ 959   51]]

N = 100
Accuracy:  0.7910416666666666
Precision:  0.5573770491803278
Recall:  0.033663366336633666
Confusion Matrix: 
[[3763   27]
 [ 976   34]]

N = 200
Accuracy:  0.7902083333333333
Precision:  0.6153846153846154
Recall:  0.007920792079207921
Confusion Matrix: 
[[3785    5]
 [1002    8]]



# Step 3. Conclusion #

Conduct a comparison among the four algorithms, considering factors such as performance, efficiency, and any additional insights you would like to share regarding this assignment.


## Model Comparison

### Linear Regression
* 由於資料集中有imbalnce的情況，使用L1時模型全部都猜Label 0，無法有效進行預測。改為L2時，有稍微改善此狀況，但還是幾乎都預測為0，因此表現仍然不佳。

### Decision Tree
* 使用Gini 或 Information Gain對模型表現並無明顯影響。
* 將模型max depth設為4，會比未做限制時有更好的表現，推測是限制深度減少了overfitting。

### SVM
* Linear Kernel: Gamma = None, C = 1, 訓練時間非常長，可能需要PCA等方法降維來提升速度，模型表現也不佳。
* RBF Kernel: Gamma = 'scale', C = 1, 訓練時間約30 sec, 不用balanced_weight的話，會因為資料分布不均而導致模型都猜同一個label；使用balanced_weight後，模型對於test set的表現會有明顯提升。

### K-Nearest Neighbor
* 設置越大的n值，模型就越傾向於預測label 0。
* 雖然訓練時，n = 100有最好的Accuracy，但那是由於大量猜0而造成的，最終選擇n = 50會得到更好的表現。

## Result Comparison

### Accuracy
* Decision Tree(64.73%) > SVM(61.14%) > Linear Regression(56.73%) > KNN (54.39%)

### Run-time
* SVM >> others

根據實驗結果，在此task中Decision Tree會是一個比較合適的選項，在擁有較短的訓練時間的同時，能得到最好的表現。